name: only_tix
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.1
  dio: ^5.5.0+1
  firebase_app_check: ^0.3.0+2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  page_transition: ^2.1.0
  path: ^1.9.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/back/
    - assets/movie.png
    - assets/genre.png
    - assets/duration.png
    - assets/star.png
    - assets/topup.png
